# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_bowl_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanktemp',
            name='date_time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
