# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_bowl_monitor', '0002_auto_20170921_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanktemp',
            name='temperature_data',
            field=models.FloatField(),
        ),
    ]
